config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Homepage where you can see all clothes
  root "items#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"\

  resources :items, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :rentals, only: [:new, :create]
  end

  resources :users, only: [:show]

  resources :rentals, only: [:index, :destroy]

  get "rentals/:id/approve", to: "rentals#approve", as: :approve_rental

  # New / Items
  # get "items/new", to: "items#new", as: :new_item
  # post "items", to: "items#create"

  # Show / Items
  # get "items/:id", to: "items#show", as: :item

  # Edit / Items
  # get "items/:id/edit", to: "items#edit", as: :edit_item
  # patch "items/:id", to: "items#update"

  # Destroy / Items
  # delete "items/:id", to: "items#destroy"

  # Profile
  # get "/profile", to: "profile#show"

  # New / Rental (Request)
  # get "rentals/new", to: "rentals#new"
  # post "rentals/new", to: "rentals#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :rentals
  has_many :users, through: :rentals
  has_many_attached :photos
  validates :name, :price, :condition, :brand, :category, presence: true
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :start_date, :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rentals
  has_many :items, through: :rentals
  validates :username, :first_name, :last_name, :email, :address, :password, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :address])
  end

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @items = Item.all
    @items = policy_scope(Item)
  end

  def show
    # @task = Task.find(params[:id]) -> refactored and added to set_item
    @rental = Rental.new
    authorize @item
  end

  def new
    @item = Item.new
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    authorize @item
    if @item.save
      redirect_to item_path(@item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # @task = Task.find(params[:id]) -> refactored and added to set_item
    authorize @item
    @item.destroy
    redirect_to root_path # status: :see_other
  end

  def edit
    # @item = Item.find(params[:id]) -> refactored and added to set_item
    authorize @item
  end

  def update
    authorize @item
    # @item = Item.find(params[:id]) -> refactored and added to set_item
    # raise
    @item.update(item_params)
    redirect_to item_path(@item)
    # else
    # render "edit" #will go back / stay on the same page
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :condition, :category, :brand, :available, photos: [])

  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :find_rental, only: [ :approve, :destroy]

  def index
    @user = current_user
    @rentals = Rental.where(user: @user)
    @rentals = policy_scope(Rental)

    @pending = @rentals.select { |rental| rental.confirmed == false }
    @confirmed = @rentals.select { |rental| rental.confirmed }
  end

  def new
    @rental = Rental.new
    @item = Item.find(params[:item_id])
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.item = Item.find(params[:item_id])
    authorize @rental
    if @rental.save!
      redirect_to rentals_path, notice: 'Rental request successful'
    else
      redirect_to new_item_rental_path(@item), status: :unprocessable_entity
    end
  end

  def approve
    @rental.confirmed = true
    authorize @rental
    if @rental.save
      redirect_to user_path(@rental.user_id), notice: 'Rental approved'
    else
      redirect_to user_path(@rental.user_id), status: :unprocessable_entity
    end
  end

  def destroy
    authorize @rental
    @rental.destroy
    redirect_to rentals_path, status: :see_other
  end

  private

  def find_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
    params.require(:rental).permit(:start_date, :end_date, :user_id, :item_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @rentals = Item.where(user: @user).map(&:rentals).flatten

    @pending = @rentals.select { |rental| rental.confirmed == false }
    @confirmed = @rentals.select { |rental| rental.confirmed }

    authorize @user
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<h1>Edit <%= @item.name %></h1>

<%= simple_form_for @item do |f| %>

<div class="web_ui__Card__card">
  <div data-testid="media-select" id="photos">
    <div class="web_ui__Label__content">
      <span>
        <h3 class="web_ui__Text__text web_ui__Text__subtitle web_ui__Text__left">
          <p>Add up to 10 photos.</p>
        </h3>&nbsp;
      </span>
    </div>
  <%= f.input :photos, class:"u-hidden", accept:"image/*", multiple:""%>
    <div class="web_ui__Label__label web_ui__Label__wide web_ui__Label__leading">
  </div>
</div>

<div class="mb-3">
    <%= f.input :name, class:"form-control", placeholder:"eg.: Cozy White Jumper", label:"Item Title" %>
</div>

<div>
    <div class="form-floating">
     <%= f.input :category, collection: ["Jumper & Sweaters", "Dresses", "Skirts", "Tops & T-shirts", "Trousers", "Active wear", "Bags", "Shoes", "Accessories"], class:"form-select", label:"Category" %>
    </div>
</div>

<div class="mb-3">
      <%= f.input :brand, class:"form-control", placeholder:"eg.: Nike, Guess", label:"Brand" %>
</div>

<div class="row">
  <div class="col">
    <%= f.input :price, class:"form-control", placeholder:"€0.00", label:"Price" %>
  </div>
  <div class="col">
    <div class="form-floating">
      <%= f.input :condition, collection: ["New with tags", "New without tags", "Used - Very good", "Used - Good", "Used - Decent", "Used - Bad"], class:"form-select", label:"Conditions"%>
    </div>
  </div>
</div>

 <div class="col-12">
    <div class="form-check">

      <%= f.input :available, as: :boolean, checked_value: 'available', unchecked_value: 'not available', class: "form-check-input" %>
    </div>
  </div>

  <%= f.button :submit, class:"btn btn-primary"%>
<% end %>

app/views/items/index.html.erb
<div class= "row justify-content-center g-5 row-cols-4"> <%# Row 2 of 2 added justify-content-center%>
    <% @items.each do |item| %>
      <div class="col"> <%# added mb-4%>
      <%# cards to take up 1/3 for medium+ devices and all space for small devices %>
        <%# div class="card h-100"%>
        <div class="card card-index" style="height: 100%;">
        <%= image_tag "#{rand(1..6)}.jpg", class: "card-img-top" %>
        <%# image_tag "#{rand(1..6)}.jpg", class: "card-img-top" %>
        <%# '.;img src="assets/images/homepage/1.jpg" class="card-img-top" #{rand(1..6)}%>
          <div class="card-body">
            <h5 class="card-title"><%= item["name"]%> </h5>
            <ul>
              <li>€<%= item["price"]%>  -  </li>
              <li><%= item["category"]%>  -  </li>
              <li><%= item["brand"]%></li>
            </ul>

            <%= link_to "See more", item_path(item), class: "btn btn-outline-secondary" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>








<!--
- Display price in this way: £ 3.50
- Display only items that are available?
    @items[available]
    @items[available]== true
- omitting condition because the seed data has weird conditions
>

app/views/items/new.html.erb
<h1>List an item </h1>

<%= simple_form_for @item do |f| %>

<div class="web_ui__Card__card">
  <div data-testid="media-select" id="photos">
    <div class="web_ui__Label__content">
      <span>
        <h3 class="web_ui__Text__text web_ui__Text__subtitle web_ui__Text__left">
          <p>Add up to 10 photos.</p>
        </h3>&nbsp;
      </span>
    </div>
  <%# f.input :photos,  class:"u-hidden", accept:"image/*", multiple:""%>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <div class="web_ui__Label__label web_ui__Label__wide web_ui__Label__leading">
  </div>
</div>

<div class="mb-3">
    <%= f.input :name, class:"form-control", placeholder:"eg.: Cozy White Jumper", label:"Item Title" %>
</div>

<div>
    <div class="form-floating">
     <%= f.input :category, collection: ["Jumper & Sweaters", "Dresses", "Skirts", "Tops & T-shirts", "Trousers", "Active wear", "Bags", "Shoes", "Accessories"], class:"form-select", label:"Category" %>
    </div>
</div>

<div class="mb-3">
      <%= f.input :brand, class:"form-control", placeholder:"eg.: Nike, Guess", label:"Brand" %>
</div>

<div class="row">
  <div class="col">
    <%= f.input :price, class:"form-control", placeholder:"€0.00", label:"Price" %>
  </div>
  <div class="col">
    <div class="form-floating">
      <%= f.input :condition, collection: ["New with tags", "New without tags", "Used - Very good", "Used - Good", "Used - Decent", "Used - Bad"], class:"form-select", label:"Conditions"%>
    </div>
  </div>
</div>

 <div class="col-12">
    <div class="form-check">

      <%= f.input :available, as: :boolean, checked_value: 'available', unchecked_value: 'not available', class: "form-check-input" %>
    </div>
  </div>

  <%= f.button :submit, class:"btn btn-primary"%>
<% end %>

app/views/items/show.html.erb
<div class= "container mb-2">

  <div class="card border-dark mb-2">
    <div class="container mb-2"> <!-- Title & Profile Link -->
      <div class="row">
        <div class="col-sm-6"> <!-- Title -->
          <br>
          <h2><%= @item.name %></h2>
        </div>
        <div class="col-sm-6"> <!-- Profile Link -->
          <br>
          <%# link_to "User Profile", user_path, class: "btn btn-outline-primary align-content-end" %>
        </div>
      </div>
    </div>
     <div class="container mb-2"> <!-- Image, Description, & Buttons -->
      <div class="row">
          <div class="col-sm-6"> <!-- Image -->
            <%= image_tag "#{rand(1..6)}.jpg", class: "card-img-top" %>
          </div>
          <div class="col-sm-6"> <!-- Description & Buttons -->
            <div class="mb-2">
              <br>
              <ul>
                <li>
                  <h3 class="card-title">
                    <% if @item.available == true %>
                      <%= "Available for rent" %>
                    <% end %>
                    <% if @item.available == false %>
                      <%= "Unavailable for rent" %>
                    <% end %>
                  </h3>
                </li>
                <li>
                  <h3 class="card-title">Price: €<%= @item.price %></h3>
                </li>
                <li>
                  <h3 class="card-title">Category: <%= @item.category %></h3>
                </li>
                <li>
                  <h3 class="card-title">Brand: <%= @item.brand %></h3>
                </li>
              </ul>
              <br>
              <!-- EDIT FORM -->
              <% if policy(@item).edit? %>
                <%= link_to "Edit Listing", edit_item_path(@item), class: "ms-3 text-muted mx-auto" %>
              <% end %>
              <!-- DELETE FORM -->
              <% if policy(@item).destroy? %>
                <%= link_to "Remove Listing", item_path(@item), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "ms-3 text-muted mx-auto" %>
              <% end %>
              <!-- RENTAL FORM -->
              <%= link_to "Rental Request Form", new_item_rental_path(@item), class: "btn btn-outline-primary" %>
              <br>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="container mb-2 justify-content-center auto"> <!-- HOME BUTTON -->
      <div class="mx-auto" style="width: 200px;">
        <br>
        <%# link_to "Back to Home", root_path, class: "btn btn-outline-primary" %>
        <br>
     </div>

</div>


<%# if image_tag  @item.photos.attached ? @item.photos : "#{rand(1..6)}.jpg" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TRECSAirbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

    <!-- add navbar before yield
    use navbar of lewagon ui kit>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rentals/index.html.erb
<h2> <strong> Upcoming rentals </strong> 🧢 </h2>

<div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col"> ❌ </th>
    </tr>
    </thead>
    <tbody>
      <% @rentals.each do |rental| %>
        <tr>
          <td><%= rental.start_date %></td>
          <td><%= rental.end_date %></td>
          <td> <%= link_to "Cancel", rental_path(rental), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rentals/new.html.erb
<h1>Rental Request Form</h1>

<!-- # FORM FOR RENTAL -->
<div class="container mt-3">
  <div class="mx-auto" style="width: 400px;">
    <h2> Submit a Rental Inquiry <h2>
  </div>
  <%= simple_form_for [@item, @rental] do |f| %>
    <div class="form-inputs">
      <%= f.input :start_date %>
      <%= f.input :end_date %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

<!-- # LINK TO HOME -->
<div class="mx-auto" style="width: 200px;">
  <%= link_to "Back to listing", item_path(@item), class: "btn btn-outline-primary" %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "RENTLY", root_path, class: "navbar-brand" %>
      <%# image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>

    <%#button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button%>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="ms-auto d-flex">
        <form class="d-flex justify-content-end">
        <%#form class="flex-grow-1 my-2 my-lg-0 me-3"%>
          <input class="form-control me-2" name="query" type="search" placeholder="Start renting" aria-label="Search" value="<%= params[:query] %>">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <%= link_to "Upload an item", new_item_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-md-2" %>


        <div class="dropdown">
          <% if user_signed_in? %>
            <a class="btn btn-outline-secondary dropdown-toggle my-2 my-sm-0 ms-md-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">Profile</a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li><%= link_to "Rentals", rentals_path, class: "dropdown-item" %></li>
                <li><%= link_to "Profile", user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
              </ul>
          <% else %>
            <a class="btn btn-outline-secondary dropdown-toggle my-2 my-sm-0 ms-md-2" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">Log In</a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li><%= link_to "Log in", new_user_session_path, class: "dropdown-item" %></li>
                <li><%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %></li>
              </ul>
          <% end %>
        </div>
        <%# refactor to dropwdown menu %>
      </div>
    </div>
  </div>
</div>
<%#= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
<%# if user_signed_in? %>
<%#= link_to "Sign out", destroy_user_session_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-md-2" %>
<%# else %>
<%#= link_to "Login", new_user_session_path, class: "nav-link" %>
<%#= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-md-2" %>
<%# end %>

app/views/users/show.html.erb
<div class="d-flex container" >
  <div class="flex-shrink-0">
    <%= image_tag "https://kitt.lewagon.com/placeholder/users/sarahlafer", class: "avatar-bordered", alt: "avatar-bordered" %>
  </div>
  <div class="flex-grow-1 ms-3">
    <h1><strong><%= @user.first_name.capitalize %></strong> </h1>
    <p>@<%= @user.username.downcase %></p>
    <p> ⭐️⭐️⭐️⭐️⭐️ (15) </p>
    <p> <strong> 100 </strong> Followers | <strong> 80 </strong> Following</p>
  </div>
</div>

<div class="container my-3">
  <% if @user.items.count > 0 %>
    <h3><strong>Renting</strong></h3>
      <div class="user-page-cards">
        <% @user.items.each do |item| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_url "#{rand(1..6)}.jpg" %>)">
          <%= item.name %> <%# would be good to have a link here to each item and also for images to not just be the link above %>
        </div>
        <% end %>
      </div>
  <% end %>
</div>

<div class="container my-5">
    <h3><strong>Confirmation</strong></h3>
      <table class="table table-borderless">
        <thead>
          <tr>
            <th scope="col">Item name</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Confirmed</th>
          </tr>
        </thead>
        <tbody>
          <% @rentals.each do |rental| %>
            <tr>
              <td><%= rental.item.name %></td>
              <td><%= rental.start_date %></td>
              <td><%= rental.end_date %></td>
              <td>
                <% if rental.confirmed == false  %>
                  <%= link_to "Approve", approve_rental_path(rental) %>
                <% else %>
                  <%= "Confirmed" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
</div>


<div class ="container my-5">
  <div class="d-flex justify-content-center">
    <% if @user.rentals.count > 0 %>
      <%= link_to "Upcoming Rentals", rentals_path, class: "btn btn-outline-primary"%>
    <% end %>
  </div>
</div>








<%# div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://media-photos.depop.com/b1/5779679/1437787993_0328f0ab999143f69e88f2f5015f39c5/P0.jpg)">
<%= image_tag "#{rand(1..6)}.jpg", class: "card-img-top" %>